# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 06:27
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=accounts.models.PhoneField(max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
