# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
