# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160116_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 16, 0, 43, 12, 344638, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
